name: Metrics

on:
  # Schedule updates (every day at 00:00)
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: olaitanojo
          template: classic
          config_timezone: America/New_York
          base: header, activity, community, repositories
          plugin_lines: yes

      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: olaitanojo
          template: classic
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 7
          plugin_activity_days: 14
          plugin_activity_filter: all
          config_timezone: America/New_York

      - name: Language activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: olaitanojo
          template: classic
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 4
          config_timezone: America/New_York

      - name: Detailed stats
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: olaitanojo
          template: classic
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
          config_timezone: America/New_York

